### ISSUE TITLE
Documents which use package pythontex do not execute their code

### ISSUE THREAD

**Issue by ohcfe** [sharelatex/sharelatex#313]
Compiling a docoment with pythonTeX involves three steps: 
 1.  running a latex-compatible tex engine,   
 2.  running pythontex.py, and finally 
 3.  running the tex engine again.

Can sharelatex be modified to do the above steps when a document which includes pythontex is compiled?

[see ctan for more information on pythontex](http://www.ctan.org/pkg/pythontex)

**Comment by jpallen** [comment]
Sorry, I doubt that this will be easy to add to ShareLaTeX. The extra steps involved in running pythontex.py would add too much complexity to our set up. If it's possible to get it to run correctly using latexmk rules then it might be doable, but other than that I doubt it's something we can support soon, sorry.

**Comment by Joehein** [comment]
@ohcfe: yes it can and it is less complicated than it sounds! I have it running on my box. (And I'm by far not an experienced hacker!) Unfortunately I cannot give access to it from outside of our LAN because of security reasons (and the firewall)...
the key points are: 
1) switch on go-mode for latexmk (no idea why this is required, but it's the result from testing, maybe someone else can shine some light on that....!). The drawback is: to have this always on slows down compilation speed (see my comments below how to switch that on or off if not needed).
For pythontex itself this is not that important since it is clever enough to know what to recompile and what not. So it should always started anyway.  
2) tell latexmk to run pythontex if a .pytxcode-file is available 
3) generate soft-links to output.pytxcode and the directory pythontex-files-output, named after your input file like main.pytxcode and pythontex-files-main in case your master input file is called main.tex (Yes this could be omitted if you rename your main .tex-file simply output.tex :-) but this is the ugly solution, but works also!)
4) using PythonTeX version >=  0.14  2014/02/07 (I'm running this one, since it works better than an earlier version who's number I can't remember anymore, what also had a different output-file structure. Moreover the older version required the Super-go-mode of latexmk to work properly.)
1) - 3) could be achieved with the help of a proper latexmkrc file. (I have added an example in this post below. It is in fact a Perl-script) To place this file were it could be found and read by latexmk, there are several possibilities: globally (not recommended because it is only useful for sharelatex but not for other users on the system), locally for the sharelatex user in its home directory as .latexmkrc or (the best solution) put it into the project tree itself. I myself used another version: I prepared several latexmkrc files and forwarded them to latexmk on the command line by the switch -r filename (see the docs of latexmk!). I made this dependent on the choice of a certain compiler in the left menu of the sharelatex project page. For that purpose I extended the list of available compilers with some py2pdflatex, py3pdflatex, py2xelatex,.... and so on. This does not only allow to switch on go-mode only in case it is really needed by pythontex, it also allows me to chose Python2 or Python3 as the python interpreter together with either XeLaTex or any other LaTeX flavour (below it is only pdfLatex used so far).
So how to change the command line of latexmk in sharelatex? You should (and have to) edit the file ~clsi/app/coffee LatexRunner.coffee. If you stay with the original file the options set in latexmkrc may be overwritten by the command line parameters. In my case I have a command line set like that:
        _py3pdflatexCommand: (mainFile) ->
                LatexRunner._latexmkBaseCommand.concat [
                        "-pdf", "-r", "/srv/www/sharelatex/lmkrc/py3pdflatexrc",
                        Path.join("$COMPILE_DIR", mainFile)
                ]
assuming you run this function for one of your compilers (for testing you can use simply one that are always there. How to extend the list of compilers is another story :-) that would be too long at that place. So you can see that I have a directory ~/lmkrc where I placed all the different latexmkrc files like the one I have attached here. I have added my complete LatexRunner.coffee also. But in order to get this working as expected you also have to modify the left menu entries at the project page as already mentioned. To avoid this for testing you can overwrite an already existing entry like the "pdflatex". After you edited the coffee script you have to recompile clsi and restart the service: in the clsi directory: grunt install and: systemctl restart sharelatex@clsi.service (I'm using systemd in the boot process, so it could be different for you).
For sure you have to adapt everything like directories etc. according to your installation. 
As an example the py3pdflatexrc I'm using is:

$pytexmod = pythontex3;

$go_mode = 1;

add_cus_dep('pytxcode', 'tex', 0, 'pythontex');
sub pythontex {
    return system("$pytexmod output") ;
}

$pdflatex = 'internal mylatex %S pdflatex -synctex=1 -interaction=batchmode %O %S';
$latex = 'internal mylatex %S latex -synctex=1 -interaction=batchmode %O %S';
$lualatex = 'internal mylatex %S lualatex -synctex=1 -interaction=batchmode %O %S';
$xelatex = 'internal mylatex %S latex -synctex=1 -interaction=batchmode %O %S';

use File::Basename;

sub mylatex {
   (my $source, my $dir, my $ext) = fileparse(shift, qr/\.tex/);
   if (! $source == 'output') {
       if (-l "$sorce.pytxcode"){
           unlink "$source.pytxcode";   
       };
       if (-l "pythontex-files-$sorce"){
           unlink "pythontex-files-$source";
       };
       symlink 'output.pytxcode', "$source.pytxcode";
       symlink 'pythontex-files-output', "pythontex-files-$source";
   };
   return system @_;
}

so you can see that all command line switches are now placed in the latexmkrc file, what makes it easier to change them rather than recompile the clsi and to restart the service.  The first line rules the Python-version to use, than the go-mode and then the pytxcode dependency of pythontex with the required command line to run it. Finally the function mylatex generates the required symlinks only if the $source is not! "output". If this is not the case nothing is needed here and the possibility of naming your main file output.tex is therefore not ruled out.
My LatexRunner.coffee looks like  

Path = require "path"
Settings = require "settings-sharelatex"
logger = require "logger-sharelatex"
Metrics = require "./Metrics"
CommandRunner = require(Settings.clsi?.commandRunner or "./CommandRunner")

module.exports = LatexRunner =
	runLatex: (project_id, options, callback = (error) ->) ->
		{directory, mainFile, compiler, timeout} = options
		compiler ||= "pdflatex"
		timeout  ||= 60000 # milliseconds

		logger.log directory: directory, compiler: compiler, timeout: timeout, mainFile: mainFile, "starting compile"

		# We want to run latexmk on the tex file which we will automatically
		# generate from the Rtex/Rmd/md file.
		mainFile = mainFile.replace(/\.(Rtex|md|Rmd)$/, ".tex")

		if compiler == "pdflatex"
			command = LatexRunner._pdflatexCommand mainFile
		else if compiler == "latex"
			command = LatexRunner._latexCommand mainFile
		else if compiler == "xelatex"
			command = LatexRunner._xelatexCommand mainFile
		else if compiler == "lualatex"
			command = LatexRunner._lualatexCommand mainFile
		else if compiler == "py3pdflatex"
			command = LatexRunner._py3pdflatexCommand mainFile
		else if compiler == "py2pdflatex"
			command = LatexRunner._py2pdflatexCommand mainFile
		else
			return callback new Error("unknown compiler: #{compiler}")

		CommandRunner.run project_id, command, directory, timeout, callback

	_latexmkBaseCommand: [ "latexmk", "-f", "-jobname=output"]

	_pdflatexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-pdf", "-r", "/srv/www/sharelatex/lmkrc/pdflatexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
	_latexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-pdfdvi", "-r", "/srv/www/sharelatex/lmkrc/latexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
	_xelatexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-xelatex", "-r", "/srv/www/sharelatex/lmkrc/xelatexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
	_lualatexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-pdf", "-r", "/srv/www/sharelatex/lmkrc/lualatexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
	_py3pdflatexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-pdf", "-r", "/srv/www/sharelatex/lmkrc/py3pdflatexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
	_py2pdflatexCommand: (mainFile) ->
		LatexRunner._latexmkBaseCommand.concat [
			"-pdf", "-r", "/srv/www/sharelatex/lmkrc/py2pdflatexrc",
			Path.join("$COMPILE_DIR", mainFile)
		]
		
I'm sure this could be programmed much cleverer since all is so similar (suggestions? the "-pdf" switch can also be moved to the latexmkrc file...), but I'm not that fluent in javascript as in Python :-) where this would be a one-liner! so I let it like that for the moment. If you apply this latexmkrc file to a non-pythontex file nothing else is left than the 

If someone could assist me on how to implement a new drop down list in the left menu of the project page (that itself is easy but some more things needed) that stores its entry in the Mongo database and that rules the compiler type used I would be happy.  In that case I could chose a tex compiler and the pythontex option separately, so that all combinations are easily possible to select, instead of having a long list of compilers... That is something I'm working on. Help is welcome!

**Comment by kvjrhall** [comment]
For someone who just wants to get pythontex running on their local sharelatex, is willing to simply edit a `.latexmkrc` file local to that project, and does not need to have a drop down, I found this this to work. You do not need to edit any server configurations, just make sure that you have the right symlinks in place.

```
$pytexmod = pythontex3;
$go_mode = 1;

add_cus_dep('pytxcode', 'tex', 0, 'pythontex'); # [1,2]
sub pythontex { return system("$pytexmod output") ; } # [2]

$pdflatex = 'internal mylatex %S pdflatex -synctex=1 -interaction=batchmode %O %S'; #[2]

use File::Basename;

sub mylatex {
    (my $source, my $dir, my $ext) = fileparse(shift, qr/.tex/);
    if (! $source == 'output') {
        if (-l "$sorce.pytxcode"){
            unlink "$source.pytxcode";
        };
        if (-l "pythontex-files-$sorce"){
            unlink "pythontex-files-$source";
        };
        symlink 'output.pytxcode', "$source.pytxcode";
        symlink 'pythontex-files-output', "pythontex-files-$source";
    };
    return system @_;
}
```
Substitute in whichever of the compiler commands your project needs based on the parent post. Now, crucial to my installation, I am using python3, but python2 is the default on the path, This means that the `pythontex` command within my docker image (instaled by default tlmgr) attempts to use python2, which caused failures. Creating an explicit symlink using the name `pythontex3` as a sibling of `pythontex` resolving to the explicit `pythontex` command (matching `$pytexmod`) was the final step.

![image](https://user-images.githubusercontent.com/63366453/81453276-2197cc00-9157-11ea-9ce8-b0d51dc35f16.png)
