### ISSUE TITLE
Support Libravatar as an alternative to Gravatar

### ISSUE THREAD

**Issue by pietsch** [sharelatex/sharelatex#320]
First of all, thank you for sharing the ShareLaTeX sources! Here is a feature request.

I am not comfortable with Gravatar tracking all users of my SL instance. Instead, I would like to set up a local [Libravatar](https://www.libravatar.org/) instance and point my SL instance to that. GitLab already offers this flexibility. Do you have plans for this?

**Comment by henryoswald** [comment]
Hi,

we don't have plans for this sorry, there are often people would like to use X rather than Y which can create confusing code, rather than using Libravatar I think the option of turning off gravatar would work well. Im going to close this because of that, if someone wants to add a don't use gravatar flag in then that would be great.
