### ISSUE TITLE
CRITICAL: Everyone can read/write to all users

### ISSUE THREAD

**Issue by d2xdt2** [sharelatex/sharelatex#321]
You need to prevent users from being able to execute bash commands from Latex.

```
\input{|"touch /tmp/aaaaaaaaaaaaaaa"}
\input{|"ls /tmp/aaaaaaaaaaaaaaa"}
\input{|"whoami"}
```
outputs
```
/tmp/aaaaaaaaaaaaaaa www-data
```

Since signing up to an account doesn't require any validation, anyone can create a bogus account (bill.gates@microsoft.com) and right after execute whatever they want on sharelatex.com including reading and write to all users data. This includes installing backdoors, bitcoin mining, you name it.

Right now you have to completely reinstall the server and notify all users that the server have been compromised and potentially **all** data might have been stolen.

**Comment by henryoswald** [comment]
Hi, on ShareLaTeX.com we run every single compile in an individual VM so you are only interacting with that virtual machine. On the open source version this is not included but is part of ShareLaTeX server pro.

**Comment by d2xdt2** [comment]
I see you have closed this bug. Aren't you concerned that anyone can execute whatever they want as the user `www-data`?

**Comment by bajo** [comment]
I share the concern from @d2xdt2 as this looks like a major deal-breaker for the open source edition.
I do not think that this should be closed without a fix for that applies to the open source edition.

**Comment by henryoswald** [comment]
Sorry if my other comment was not clear:
- It is not possible for anyone to execute whatever they want as the user www-data on ShareLaTeX.com as these commands are run inside of a VM which are not shared between projects.
- It is possible todo this on the open source version, but this is not an issue as the open source version is not designed to be run by large organisations. The open source version does not include the ability for public registration, the admin adds users they trust to the system.
- ShareLaTeX Server Pro (https://www.sharelatex.com/university/onsite.html) includes the VM tool making compiles secure which is useful for larger organisations.

**Comment by d2xdt2** [comment]
The above commands did I run on sharelatex.com. See `/tmp` and you will see my test file.

When you say VM, do you mean KVM or Docker?

`\input{|"cat /etc/issue"}` gives that sharelatex.com is running Ubuntu 12.04.5 LTS, so no SELinux. I hope you then atleast AppArmor is configured and running.

If KVM, have you patched against the VENOM bug?

Docker does not protect or isolate in anyway. A little if you have CentOS with SELinux enabled, other wise it is trivial to break out.

Still, anyone have full `www-data` access, so they can run whatever they want on sharelatex.com, this needs to be fixed.

Is it ok with you if I try and break out of the VM you are mentioning? It won't take long, if ShareLatex's security relies on Docker without SELinux.

**Comment by jpallen** [comment]
If you do find any security vulnerabilities with our sandboxing, please disclose them with an email to team@sharelatex.com (See https://www.sharelatex.com/security), not as a public issue where they will be publicly disclosed before we have a chance to patch them.

You are welcome to try to break out of our sandboxing, so long as you do so in a responsible way that doesn't risk the data of other users. If you do find any problems, please disclose them to us in a private so that we can discuss how to patch them before making it public.

**Comment by d2xdt2** [comment]
You really need to take security of the users data more seriously. I am saying this for your and your company's own good. Having full `www-data` access being it sandboxed or not, does render the host compromised.

The harmless hacker will use sharelatex.com for SSH proxies or Bitcoin mining, and the not so harmless hackers will gzip all user data and files and share them as a torrent, hence put sharelatex.com out of business once and for all. Personally you can go bankrupt from law suites as ShareLatex.com is advertised for Universities which might loose millions of dollars of having their articles stolen and published before their patent they applied for have been granted rendering their research public domain.

Secondly, ShareLatex.com needs to validate the email addresses when users are signing up. Anyone can create an account of any of your customers TLD's. First of all by using a TLD of any of your customers, anyone gets the PRO subscription and secondly anyone can send share requests and look like a legitimate user of the TLD.

I am pinning this out, as I mentioned it in the OP, and no comments have been written about this.

**Comment by jpallen** [comment]
@d2xdt2 Sorry, we don't mean to dismiss your concerns here. Your right that security is really important, particularly around the confidentiality of data. However, we're not aware of any vulnerabilities in sharelatex.com that put this at risk. We will take quick action if/when we become aware of such things. The things you have raised, while they look like they might be be a problem on the surface, do not present a vulnerability that could allow access to other users' data. The www-data access is only inside the sandbox for that one project. The files that are available to read and write are only related to that project or that sandbox, and while we provide a full system (so you can do seemingly scary things like read /etc/passwd), this doesn't provide access to any other data.

Things that would be a problem include being able to break out of the sandbox and read other user's data, execute programs on the host machine, starve other projects of resources, and any other 'breakout' type attacks. However, we are not at the moment aware of any attacks that can achieve this (and have patched quickly any such vulnerabilities when previously responsibly disclosed to us). If you do find a vulnerability like this, please let us know via the appropriate channel and we will address it ASAP.

We're working on validation for emails where it matters: like you say, when there is a TLD that gets special treatment, to prevent it being taken advantage of. However, this is only in response to a recent change in the way our subscription system works for a small number of groups. Currently subscriptions are managed manually, and accounts must be added by hand, so there is no risk of exploitation here. Again, if there is something specific which you think can be exploited here, please let us know via the team@sharelatex.com email address, with a proof of concept if possible.

> I am pinning this out, as I mentioned it in the OP, and no comments have been written about this.

I'm afraid I don't quite get the meaning of this sentence, sorry.

**Comment by d2xdt2** [comment]
The bad guy the gzips all the user data and will not write to you in advance to let you know about the vulnerability he found. You will only know about this when it is too late. My point being, not knowing about any vulnerabilities is not an argument that there aren't any.

Seriously it is a regex one-liner to fix this critical hole. Why don't you want to fix it?

**Comment by jpallen** [comment]
You can say that about any system though surely? There might be a vulnerability anywhere, and you never know about them in advance until they are exploited or disclosed.

I don't think I follow what it is that you want us to fix here, sorry. We purposefully give you a full system with the ability to execute code, so that LaTeX packages like minted, which rely on executing external python scripts can work. We also support knitr, which lets you run arbitrary R code. We have set our sandbox up with this use case in mind.

What is the regex one-liner that you had in mind roughly? Just in case I'm misunderstanding what you see as the issue here.

Sorry for any confusion here. It's not due to lack of wanting to act on our side, but rather than we don't see what exactly you think is a problem and should be fixed.

**Comment by d2xdt2** [comment]
Ok, so if you allow for Python and R scripts to be executed, then it is of course a conscious decision that the security of other users data is guarded by the Docker container.

The regex one-liner I mentioned is one that removes `\input{|"..."}`.

Being able to execute bash, python and R is awesome, as it can be used to very productive things (e.g. include shared files between projects), but it is a huge risk you are taking to give those options on a host that holds other users data.

**Comment by jpallen** [comment]
In the early days of ShareLaTeX, before we had a full sandbox, we did consider blacklisting some things like `\input{|...}`, but since LaTeX is a full language itself, it's possible to redefine all commands arbitrarily and heavily obfuscate code, so a white/blacklist approach isn't feasible either.

We're confident in our sandboxing, and it has stood up to a few penetration tests/attempts, with some minor vulnerabilities patched (none that would have allowed arbitrary access to other user's data). We very much welcome people trying to responsibly discover vulnerabilities in this part of the system, so if you do come across anything that seems like an issue, please do let us know! (via email though, not publicly at first).

**Comment by jidhub** [comment]
This bug has been presented as a feature. This feature allows sharing .aux content between latex projects, see this blog post https://www.overleaf.com/learn/latex/Articles/How_to_use_latexmkrc_with_Overleaf

I am thinking of also using this "feature" to get access to the full history of my overleaf.com account, see https://github.com/overleaf/overleaf/issues/512

**Comment by William957-web** [comment]
> You need to prevent users from being able to execute bash commands from Latex.
> 
> ```
> \input{|"touch /tmp/aaaaaaaaaaaaaaa"}
> \input{|"ls /tmp/aaaaaaaaaaaaaaa"}
> \input{|"whoami"}
> ```
> 
> outputs
> 
> ```
> /tmp/aaaaaaaaaaaaaaa www-data
> ```
> 
> Since signing up to an account doesn't require any validation, anyone can create a bogus account ([bill.gates@microsoft.com](mailto:bill.gates@microsoft.com)) and right after execute whatever they want on sharelatex.com including reading and write to all users data. This includes installing backdoors, bitcoin mining, you name it.

Can you explain the principle of this feature(~vulnerability~).
