### ISSUE TITLE
Trouble using Knitr in the Docker image

### ISSUE THREAD

**Issue by ConorIA** [sharelatex/sharelatex#460]
I have been trying to get knitr set up for use with ShareLatex by following info from [here](http://tex.stackexchange.com/questions/247369/install-knitr-on-own-sharelatex-server) and [here](http://git.leg.ufpr.br/leg/sharelatex-rautu). I ran the following series of command from within the docker image: 

```
echo "deb https://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list 
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
apt-get update
apt-get install r-base r-base-core r-base-dev
mkdir -p /usr/local/share/latexmk/
cat << EOF > /root/.latexmkrc
my \$root_file = \$ARGV[-1];

add_cus_dep( 'Rtex', 'tex', 0, 'rtex_to_tex');
sub rtex_to_tex {
    do_knitr("\$_[0].Rtex");
}

sub do_knitr {
    my \$dirname = dirname \$_[0];
    my \$basename = basename \$_[0];
    system("Rscript -e \\"library('knitr'); setwd('\$dirname'); knit('\$basename')\\"");
}

my \$rtex_file = \$root_file =~ s/\\.tex$/.Rtex/r;
unless (-e \$root_file) {
    if (-e \$rtex_file) {
        do_knitr(\$rtex_file);
    }
}

EOF
R -q -e "install.packages('knitr', repos='http://cran.rstudio.com/')"
```

Unfortunately, after restarting the Docker image, I am still recieving this error when trying to compile a .Rtex file: 

```
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=latex 2016.6.30)  22 AUG 2016 00:31
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**main.tex
! Emergency stop.
<*> main.tex

*** (job aborted, file error in nonstop mode)
```

I should mention that I have tried pasting the latexmkrc info into two different files:

1) `/root/.latexmkrc`
2) `/usr/local/share/latexmk/LatexMk`

Neither works, so far!

**Comment by zeigerpuppy** [comment]
I have the same problem.  I wonder if we're missing the install of a library, seems strange that we need to create the /usr/local/share/latexmk folder.

**Comment by zeigerpuppy** [comment]
any update on this issue, I've tried editing the files:

1. /root/.latexmkrc
2. /usr/local/share/latexmk/LatexMk
3. /root/.latexmk

none of these work (smae error as @ConorIA has above).

do we need to edit `/etc/LatexMk` maybe?

**Comment by joukhaha** [comment]
Not a dev or even a connaisseur, but I managed to get this working after a lot of struggle. The solution is possibly not the best one, as it required some additional tweaks to make synctex (syncing the position between the pdf and the editor) working, but at least it works now.

I'll try to run through the main steps below (as far as I remember them), but if someone actually goes through the steps it'd be nice to complete the guide by adding the possibly missing non-trivial steps:

0. To make knitr and patchsynctex work, you first need to have a proper R environment installed in your sharelatex docker (to install the needed R libraries you can do 'packages.install("knitr", dependencies=TRUE)' and same for patchsynctex (and knitcitations if you like). It also seems that you need to add the cran repository to get a sufficiently recent version of R.

1. Make sure your sharelatex is running (sudo docker start sharelatex) and get to sharelatex command line (sudo docker exec -it sharelatex bash). In fact this is the environment the R installation should also be made in.

2. In the docker filesystem edit /var/www/sharelatex/clsi/app/js/LatexRunner.js by modifying the command _pdflatexCommand close to the end of the file to become
      return LatexRunner._latexmkBaseCommand.concat(["-pdf", "-e", "$pdflatex='pdflatex -synctex=1 -shell-escape -interaction=batchmode %O %S'", "-r", "/usr/local/share/latexmk/latexmk", Path.join("$COMPILE_DIR", mainFile)]);

(all in single line). This adds the shell-escape option (don't do this unless you trust the users to behave, google it) and determines that the configuration file latexmk will be loaded after -e redefines the pdflatex command to be able to run patchsynctex after pdflatex finishes.

3. Create the file /usr/local/share/latexmk/latexmk (I actually also have the latexmkrc next to this file, but shouldn't matter) with the content

# /usr/local/share/latexmk/latexmk
my $root_file = $ARGV[-1];
my $base_file = $root_file =~ s/\.(Rtex|Rnw|tex)$//r;
my $tex_file = $base_file . '.tex';
my $rtex_file = $base_file . '.Rtex';
my $rnw_file = $base_file . '.Rnw';
my $base_dir = dirname $base_file;
$root_file = $base_file;

#print "my base file is $base_file\n";
#print "my rnw file is $rnw_file\n";
#print "my root file is $root_file\n";
#print "my tex file is $tex_file\n";
#print "my rtex file is $rtex_file\n";

add_cus_dep( 'Rnw', 'tex', 0, 'rnw_to_tex');
add_cus_dep( 'Rtex', 'tex', 0, 'rtex_to_tex');

unless (-e $tex_file) {
    if (-e $rnw_file) {
        do_knitr($rnw_file);
    }
    if (-e $rtex_file) {
        do_knitr($rtex_file);
    }
}
#show_cus_dep();

my $pdf_latex_old = $pdflatex =~ s/%S/$tex_file/r;

$pdflatex = $pdf_latex_old ."; Rscript -e 'library(patchSynctex); setwd(%Z); patchSynctex(\\"".basename($base_file)."\\",%B,verbose=TRUE) ' "; 

sub rtex_to_tex {
    print "Knitting Rtex file\n";
    do_knitr("$_[0].Rtex");
}

sub rnw_to_tex {
    print "Knitting Rnw file\n";
    do_knitr("$_[0].Rnw");
}

sub do_knitr {
    my $dirname = dirname $_[0];
    my $basename = basename $_[0];
    print "Now Knitting $basename\n";
    system("Rscript -e \\"options(knitr.package.concordance=TRUE);library('knitr'); setwd('$dirname'); knit('$basename')\\"");
}

This makes latexmk to run knitr on both Rtex and Rnw files - however, as only Rnw files are supported by patchsynctex, only they offer the synctex features in the sharelatex editor. If you want to use knitr you should use a file named *.Rnw in sharelatex. Note that at least in the preview mode the file listing above DOES NOT ESCAPE the quotation marks correctly so I've replaced the escaped \" with \\" which probably looks correct in actual view.

At the moment these modification seem to have enabled using knitr in community sharelatex. There may, however, be some steps I've forgotten because this really took a lot of time and trials to make it work. In that case please add a comment to this thread...

**Comment by ConorIA** [comment]
Thanks for the guidance @joukhaha! I'll see if I can't whip this up into a script when I have a little bit of free time.

**Comment by ConorIA** [comment]
There it is: [Original on GitLab](https://gitlab.com/ConorIA/dockerfiles/tree/master/sharelatex-knitr) [GitHub mirror](https://github.com/ConorIA/dockerfiles/tree/master/sharelatex-knitr)

It would be great if folks could test this Dockerfile. If everything seems to be working, I can push it to Docker Hub, where I can set it to automatically build whenever the ShareLaTeX devs push an updated image.

**Comment by zeigerpuppy** [comment]
Thanks for scripting this us, @ConorIA!
I have just updated my sharelatex docker to 0.6.3 and enabled shell-escape support.  I am now hoping to implement this patch.  

I can see the files I'd need to patch manually but would like to try the automated way.
I am still a little new to docker so I'm not quite sure how to apply the script to my current install.  If I have a docker container called `sharelatex` running, how would I enable the patching of it with your files?

**Comment by zeigerpuppy** [comment]
I can confirm that these instructions work well.  There is a small change with the `/var/www/sharelatex/clsi/app/js/LatexRunner.js` file as the syntax has changed slightly in the latest docker versions (I can confirm the following works with v0.6.3).

```
_latexmkBaseCommand: ((Settings != null ? (_ref1 = Settings.clsi) != null ? _ref1.latexmkCommandPrefix : void 0 : void 0) || []).concat(["latexmk", "-cd", "-f", "-jobname=output", "-auxdir=$COMPILE_DIR", "-outdir=$COMPILE_DIR", "-synctex=1", "-shell-escape", "-interaction=batchmode", "-r", "/usr/local/share/latexmk/latexmk"]),
```

So happy that `knitr` is working!

**Comment by ConorIA** [comment]
Hi @zeigerpuppy, thanks for the update! I'm glad you got it working. Do we still need to update the `_pdflatexCommand` as per my current Dockerfile, or just the `_latexmkBaseCommand`? I'd like to update the Dockerfile but I'm overseas and my internet connection doesn't lend itself to much experimentation, unfortunately.

**Comment by zeigerpuppy** [comment]
it works with just updating `_latexmkBaseCommand`, the `_pdflatexCommand` calls this function.

**Comment by ConorIA** [comment]
Great. It's updated now with an automated build on Docker Hub under conoria/sharelatex-knitr.
