### ISSUE TITLE
error creating admin user

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/sharelatex#479]
I have installed sharelatex on Ubuntu 14.0.4 with the instructions from the Quickstart guide.  Mongo and redis are runing in their own docker containers as shareredis and sharemongo (as suggested in https://github.com/sharelatex/sharelatex-docker-image/issues/2.

I can access the sharelatex instance on port 5000 and everything looks good in the logs.  However, when I try to add an admin user, I get:

`docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email joe@example.com"`

```
Warning: Task "create-admin-user" not found. Use --force to continue.

Aborted due to warnings.
```

I wondering if something has changed in the process to create the admin user, or if I'm missing a step?

**Comment by zeigerpuppy** [comment]
I found this similar error: https://github.com/sharelatex/web-sharelatex/issues/182

But the solution there (going to /var/www/sharelatex/web) is not applicable, we're already in the web directory.

**Comment by Coksnuss** [comment]
I can confirm that the tag `v0.2.0` is disfunctional and the wiki documentation is outdated. This tag is automatically loaded by docker when using the installation instructions in the wiki. Commit 7bfa3f9 introduces a new syntax for the grunt task that creates an admin user (`user:create-admin` instead of `create-admin-user`)
Related tickets: #462, #470.

I have no experience with docker or grunt, but my workaround for creating an admin user is this:
Open a shell in the docker instance via `docker exec -i -t sharelatex /bin/bash` and execute the following steps:

1. `cd /var/www/sharelatex/`
1. `vim grunt/CreateAndDestoryUsers.coffee`
  - Copy the registerTask method (line 4 to 36) by placing the cursor in line 4 and instruct vim to copy the following 33 lines via `y33y`
 - Exit via `:q`
1. `vim Gruntfile.coffee`
 - Navigate to line 116 (`:116` or use arrow keys)
 - Paste the copied lines below the definition of the *migrate* task via `p`
 - Edit the require path for the `UserRegistrationHandler` and `OneTimeTokenHandler` by removing the first dot of `../` (-> `./`)
 - Save and close the file via `:wq`

Be careful when executing the steps above. Docker has problems in handling some keys (like `del` or `pagedown`). This can lead to a corrupted file. Only use the arrow keys for navigating and use backspace in insert-mode instead of the `del` key to delete character sequences.

Now you should be able to create a new admin user via `grunt user:create-admin --email your@email.tld`

**Comment by zeigerpuppy** [comment]
Thank you so much, that worked well.

ps. here's a tip to get better terminal functionality in docker exec, connect with:
```
docker exec -ti sharelatex env TERM=xterm bash -l
```

**Comment by zeigerpuppy** [comment]
I'm not convinced that the docker way is any easier for this install, perhaps a non-dockerised install wiki article would be good too

**Comment by Coksnuss** [comment]
Thanks for the tip.

> I'm not convinced that the docker way is any easier for this install, perhaps a non-dockerised install wiki article would be good too

It was a breeze when i tried it last time (few months ago). It seems that new commits in the repository are not tested very well but overall I like the 'docker-way' of installing it.

**Comment by zeigerpuppy** [comment]
I've had another look and creating an admin user can be done without editing the .coffee files by using the command:

```
docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/; grunt user:create-admin --email admin@test.com"
```

Thanks again for getting me on the right track!

**Comment by Coksnuss** [comment]
For some reason I can not use the command directly. But glad it works for you.

**Comment by M-Gregoire** [comment]
Thank you @zeigerpuppy ! I was getting crazy on this

**Comment by henryoswald** [comment]
sorry for the bad docs, they have been updated now.

**Comment by mimischi** [comment]
@henryoswald Sorry but I'm still not able to create an admin user. I also do not see any updated documentation (everything was updated 5 days ago).

Neither ``user:create-admin`` nor ``create-admin-user`` work as a ``grunt`` command. I'm using the current ``master`` branch and build the system on Ubuntu 16.04 with Docker versions as follows:

```
root@server:~/sharelatex# docker -v
Docker version 1.12.3, build 6b644ec
root@server:~/sharelatex# docker-compose -v
docker-compose version 1.8.1, build 878cff1
```

The system is up and running, but without any admin users I can't do anything.

**Comment by Coksnuss** [comment]
The wiki was updated accordingly: https://github.com/sharelatex/sharelatex/wiki/Creating-and-managing-users 

I think its easiest for us to help you if you post output the following command produce on your machine:
```
docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email joe@example.com"
```

**Comment by mimischi** [comment]
@Coksnuss thanks for getting back.

The output is as follows:
```
root@server:~/sharelatex# docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email joe@example.com"
Warning: Task "user:create-admin" not found. Use --force to continue.

Aborted due to warnings.
```

The Git output (to make sure that I'm on the newest version) is: 
```
root@server:~/sharelatex# git remote -v
origin	https://github.com/sharelatex/sharelatex.git (fetch)
origin	https://github.com/sharelatex/sharelatex.git (push)
root@server:~/sharelatex# git pull origin
Already up-to-date.
root@server:~/sharelatex# git branch
* master```

**Comment by henryoswald** [comment]
are you doing a git pull inside the docker image? That is not recommended if you are, there can be bugs and incompatibilities. It also won't update all the 10+ other repos. You are best taking the latest docker image which will work for you.

**Comment by mimischi** [comment]
No, I cloned this repository to my Ubuntu 16.04 server (host) and used ``docker-compose build`` and ``docker-compose up`` to create the containers. The note on ``/var/www/sharelatex/Gruntfile.coffee`` was meant to reference the file inside that Docker container and not on the host.

**Comment by Coksnuss** [comment]
I am afraid that this is the same error that I have experienced. But since zeigerpuppy said it worked for him, I thought that this is related to my environment.

I have no experience with Grunt. But unless the files inside the `grunt` directory of this repository (namely `grunt/CreateAndDestoryUsers.coffee) are automagically loaded, I do not understand how the code inside this file could ever be executed. I do not see how Gruntfile.coffee does include this file.

**Comment by mimischi** [comment]
Right. The aforementioned [commit](https://github.com/sharelatex/sharelatex/commit/7bfa3f97e78d09329a7f727ee969cc674c7dce6a) does not seem to be in place anymore when looking at the [current file](https://github.com/sharelatex/sharelatex/blob/master/Gruntfile.coffee#L17-L23).

As mentioned before, inside my sharelatex container there is no ``/var/www/sharelatex/grunt`` folder, while I do have that inside the Git repository on my host.

**Comment by Coksnuss** [comment]
I think the line has just moved to the [bottom of the file](https://github.com/sharelatex/sharelatex/blob/master/Gruntfile.coffee#L245) (Related commit: 85059077ed27f0c710e900372b633702a5861799). But still, how is it supposed to include the files inside the grunt directory?

Its odd that you are missing the `/var/www/sharelatex/grunt` folder. My docker container uses commit 8ebbffe4ba372f3e1ec391d910f7a60b333f33b6 of this repo and the directory is present.
```
coksnuss@vm:~$ docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; git rev-parse HEAD"
8ebbffe4ba372f3e1ec391d910f7a60b333f33b6 
```

**Comment by mimischi** [comment]
Wow this feels stupid. But I just managed to get it to work.

I just noticed that inside the Docker container files inside /var/www/sharelatex were created on March 2015, even after removing the container and building it from scratch. It came to my mind that after upgrading vom Ubuntu 14.04 to 16.04, I had to re-install Docker. Obviously it stored an old image of ``sharelatex/sharelatex`` (that was downloaded over a year ago) somewhere and was always building that. Doing ``docker pull sharelatex/sharelatex`` grabbed the new image and creating the system with docker-compose worked now.

Thanks for the quick responses guys. The fault was on my side!
