### ISSUE TITLE
Projects gone!

### ISSUE THREAD

**Issue by yunyun630** [sharelatex/sharelatex#575]
(If you have a feature request, or bug with ShareLaTeX, please file an issue at https://github.com/sharelatex/web-sharelatex. This repository should **only be used for installation and maintenance problems** of ShareLaTeX Community Edition)

## Projects gone!
All the projects I created are gone. 
![sharelatex](https://user-images.githubusercontent.com/34975019/34459131-cd07cdf4-edb4-11e7-9365-627adf482d00.png)

## Logs and errors

Not found

Sorry, we can't find the page you are looking for.

## Screenshots

Please provide any screenshots of errors in ShareLaTeX Community Edition.

**Comment by jdleesmiller** [comment]
Hello, we need more detailed information if we're going to be able to help with this. If this is on sharelatex.com, please contact sharelatex support rather than opening an issue here on github. If this is on a local installation of ShareLaTeX, please consult the documentation (https://github.com/sharelatex/sharelatex/wiki) and if there is no resolution there then please reopen this issue with more details about how exactly you got to this point.
