### ISSUE TITLE
Upgrade sharelatex 0.2.0

### ISSUE THREAD

**Issue by salleman33** [sharelatex/sharelatex#594]
Hi, 

I have an instance of the community Sharelatex 2014 (release 0.2.0 on git repositories). I looking for any update available. I would upgrade to an community version without using the docker image (I want to install sharelatex directly on the server to changes some features).

On the url : https://github.com/sharelatex/sharelatex/wiki/Dependencies, links to 'Production Installation Instructions' or 'Setting up a Development Environment' are dead and they redirect to https://github.com/sharelatex/sharelatex/wiki
On this page that there are releases until 0.6.0 for community version. How can I install one of these ? 

Regards

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. Good point about those links. I think for now I will remove them, until we have more docs. We've since moved to an easier install where the Mongo and Redis dependencies are also managed under docker using a docker-compose file, as mentioned in the quickstart: https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide

If you have Mongo and Redis installed outside of docker(-compose), I think the upgrading instructions here are still current (you should just need to change the version at the end of the last command):
https://github.com/sharelatex/sharelatex/wiki/Upgrading-Containers

You may also want to review the release notes for the intervening versions here: https://github.com/sharelatex/sharelatex/wiki

**Comment by salleman33** [comment]
Thanks for your answer. 
So, it's not possible to install sharelatex directly on the system, without docker ? I have to patch the code of web-sharelatex to adapt some features. 
Last question : is the docker version reliable for production setup ?

**Comment by jdleesmiller** [comment]
It's not impossible to install sharelatex directly, but I'm afraid we can't offer support outside of the docker environment --- there are a lot of dependencies, and docker allows us to fix them to avoid issues.

We've been running docker in production in various ways for quite a while, and we haven't had much trouble with it. HTH!

**Comment by blubbsy** [comment]
@Sallemann33 i had sharelatex running directly on my server (debian sid) during my PhD and it was quite a pain in the ass to manage and update it properly.

**Comment by salleman33** [comment]
Yes, i'm afraid with that :/ 
Why there is no git tag for releases after 0.2.0 ?
