### ISSUE TITLE
systemd service file for sharelatex

### ISSUE THREAD

**Issue by canercandan** [sharelatex/sharelatex#94]
I wanted to share the file that I am using to make sharelatex works alongside systemd (available on Archlinux for instance).

Here it is:
```
[Unit]
Description=ShareLatex
After=syslog.target
After=network.target

[Service]
Type=simple
User=root
Group=root
PermissionsStartOnly=true
ExecStart=/usr/share/webapps/sharelatex/start.sh

[Install]
WantedBy=multi-user.target
```

The content can be saved to the path /usr/lib/systemd/system/sharelatex.service

**Comment by leadmocha** [comment]
Hi @jpallen I created the following wiki https://github.com/sharelatex/sharelatex/wiki/Setup-ShareLaTeX-Services-with-systemd

Is this enough to close this issue?   Also, should I update the Arch instructions to match this page? They suggest creating multiple files there, but with systemd, you can use one single file as a template to manage **all** services.

Thanks!

**Comment by jpallen** [comment]
That wiki page looks great, thank you very much! I'm not very familiar with systemd, but if the way you have documented is better (objectively?) then feel free to update the Arch documentation to match. In general I'd always prefer to have a single canonical method of doing things documented rather than split approaches in the same wiki.

**Comment by samvv** [comment]
Looking good (y) Though I haven't yet have had the time to try it. And yes, a lot of Linux-based OSes are making the transition to systemd, including Debian in its next release.

**Comment by PandaScience** [comment]
Hi there. Thanks for the instructions! I just tried them on a fresh Debian 8 installation with the current sharelatex release and encountered a strange failure. maybe you can help me on this. 

systemd seems to have trouble to find `/etc/sharelatex/start_modules.sh` when starting the template service. It's also listed in `systemctl --failure`. `systemctl status sharelatex@template.service` gives

>root@sharelatex:~$ systemctl status sharelatex@template.service 
>● sharelatex@template.service - ShareLaTeX A web-based collaborative LaTeX editor
>   Loaded: loaded (/etc/systemd/system/sharelatex@.service; enabled)
>   Active: failed (Result: exit-code) since Mon 2015-03-30 18:26:15 CEST; 3s ago
>    Docs: https://github.com/sharelatex/sharelatex/wiki
>  Process: 914 ExecStart=/etc/sharelatex/start_module.sh %i (code=exited, status=200/CHDIR)
> Main PID: 914 (code=exited, status=200/CHDIR)
>
>Mar 30 18:26:15 sharelatex systemd[914]: Failed at step CHDIR spawning /etc/sharelatex/start_module.sh: No such fil...ectory
>Mar 30 18:26:15 sharelatex systemd[1]: sharelatex@template.service: main process exited, code=exited, status=200/CHDIR
>Mar 30 18:26:15 sharelatex systemd[1]: Unit sharelatex@template.service entered failed state.
>Hint: Some lines were ellipsized, use -l to show in full.

Could be that bug here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759320
but fixing it like suggested there didn't change anything. Any ideas?

**Comment by leadmocha** [comment]
Hey @PandaScience: Just to confirm, the file /etc/sharelatex/start_module.sh exists, correct?

That is 'module' singular, without the 's'.  Can you confirm?

**Comment by PandaScience** [comment]
Hi. Thx for the quick reply. Yes, the file exists and it's "module" without s - just a typo, sry. 
I already tried to chmod the file to sharelatex:sharelatex since the user running the cmd is sharelatex:sharelatex and according to the instructions, the owner is initially root, but that didn't change anything.

**Comment by ccgurley** [comment]
Hi,

I seem to be having some issues with the template portion as well. Everything else (sharelatex@web, etc) starts fine.
sharelatex@template.service - ShareLaTeX A web-based collaborative LaTeX editor
   Loaded: loaded (/etc/systemd/system/sharelatex@.service; enabled)
   Active: failed (Result: exit-code) since Fri 2015-08-28 09:47:15 EDT; 4s ago
     Docs: https://github.com/sharelatex/sharelatex/wiki
  Process: 2793 ExecStart=/etc/sharelatex/start_module.sh %i (code=exited, status=200/CHDIR)
 Main PID: 2793 (code=exited, status=200/CHDIR)

Any help would be appreciated,
Thanks.
